# Generated by Django 5.2 on 2025-04-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRoute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='route_name',
        ),
    ]
