# Generated by Django 5.2 on 2025-04-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRoute', '0002_rename_name_route_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='ImageRoute.user'),
        ),
        migrations.AddField(
            model_name='route',
            name='map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='ImageRoute.map'),
        ),
    ]
