# Generated by Django 5.2 on 2025-04-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRoute', '0006_remove_route_length_remove_route_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ImageRoute/backgrounds/'),
        ),
    ]
