# Generated by Django 5.2 on 2025-04-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRoute', '0007_alter_backgroundimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
