# Generated by Django 5.2 on 2025-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRoute', '0008_alter_backgroundimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
