# Generated by Django 5.2 on 2025-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRoute', '0010_gameboard_dot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameboard',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gameboard',
            name='dots_data',
            field=models.JSONField(null=True),
        ),
    ]
