# Generated by Django 5.2 on 2025-06-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRoute', '0011_remove_gameboard_created_at_gameboard_dots_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameboard',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='gameboard',
            name='dots_data',
        ),
        migrations.AddField(
            model_name='gameboard',
            name='dots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Dot',
        ),
    ]
